syntax = "proto3";

option java_multiple_files = true;
option java_package = "org.example";

service AcceptorService {
  rpc Promise(PromiseRequest) returns (PromiseResponse) {}
  rpc Accept(AcceptRequest) returns (AcceptResponse) {}
  rpc Inform(InformRequest) returns (InformResponse) {}
}

message PromiseRequest {
  int32 proposal_number = 1;
  int32 sequence_number = 2;
}

message PromiseResponse {
  enum Status {
    OK = 0;
    REJECT = 1;
  }

  Status status = 1;
  int32 accepted_proposal_number = 2;
  string accepted_value = 3;
}

message AcceptRequest {
  int32 proposal_number = 1;
  string proposal_value = 2;
  int32 sequence_number = 3;
}

message AcceptResponse {
  enum Status {
    OK = 0;
    REJECT = 1;
  }
  Status status = 1;
}

message InformRequest {

}

message InformResponse {
  message Pair {
    int32 sequence_number = 1;
    string accepted_value = 2;
  }
  repeated Pair acceptedValues = 1;
}